pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        // Simple Java Hello World
        sh '''
          echo "public class HelloWorld {
              public static void main(String[] args) {
                  System.out.println(\\"Hello from Back-end (Java)\\");
              }
          }" > HelloWorld.java
          javac HelloWorld.java
          java HelloWorld
        '''
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        // Simple Node.js Hello World
        sh '''
          echo "console.log('Hello from Front-end (Node.js)');" > app.js
          node app.js
        '''
      }
    }

    stage('Database') {
      agent {
        docker { image 'mysql:8.0' }
      }
      environment {
        MYSQL_ROOT_PASSWORD = 'rootpass'
        MYSQL_DATABASE = 'testdb'
      }
      steps {
        // Print MySQL version and create a sample DB
        sh '''
          echo "Hello from Database (MySQL)"
          mysqld --version
        '''
      }
    }
  }
}
